### ISSUE TITLE
Applying algorithm to linear envelope

### ISSUE THREAD

**Issue by SlootY98** [GallVp/emgGO#7]
Hi,

First of all, thanks for sharing your GUI! It looks great and everything is working. However, when I use my EMG data it just does not identifies the right on- and offset moments of muscle activation. When I tried importing the linear envelope of my EMG data, it works quite well at first glance (in my opinion). Do you know if using the linear envelope will distort my outcomes? 
![Schermafbeelding 2023-02-06 120307](https://user-images.githubusercontent.com/124575384/216955528-91ac32d5-d5e1-4132-9d5e-107a0038d22b.jpg)
![Schermafbeelding 2023-02-06 115854](https://user-images.githubusercontent.com/124575384/216955533-30456ac4-4e0e-4613-8043-cb564d3e746d.jpg)

**Comment by GallVp** [comment]
Hi @SlootY98 

Thank you for the feedback.

The premise of this toolbox is that the expert (in this case, you) make the final judgement on onset/offset timing. The toolbox can help you identify set number of activations and also provide you interactive feedback for parameter manipulation.

If you think that the envelope gives you better results, that's great. Use the envelope.

One thing though. It might be that the onsets/offsets for the envelope and the filtered data are nearly identical, and the envelope results look better because the envelope provides a smooth background. To address this point, I suggest to detect activations from the filtered data and from the envelope for 3-5 files. Then, analyse the differences across the two sets of activations.

Cheers
Usman R.
